# Build settings
[build]

  command = "gunicorn -c Personal Website/gunicorn_config.py app:app"
  publish = "static"        # Replace with the path to your static files (JS, CSS, etc.)

# Optional: Environment variables
[build.environment]
  FLASK_ENV = "production" # Set Flask environment to production