# Build settings
[build]
  command = "python app.py" # Replace with your Flask application start command
  publish = "static"        # Replace with the path to your static files (JS, CSS, etc.)

# Optional: Environment variables
[build.environment]
  FLASK_ENV = "production" # Set Flask environment to production